/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155Mock__factory } from "./ERC1155Mock__factory";
export { ERC721Mock__factory } from "./ERC721Mock__factory";
