/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as discountDbSol from "./DiscountDB.sol";
export type { discountDbSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as standards from "./standards";
export type { standards };
import type * as test from "./test";
export type { test };
export type { KlayLink } from "./KlayLink";
export type { KlayLinkMinter } from "./KlayLinkMinter";
