/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDiscountDB } from "./IDiscountDB";
export type { IERC721Metadata } from "./IERC721Metadata";
export type { IKlayLink } from "./IKlayLink";
export type { IKlayLinkMinter } from "./IKlayLinkMinter";
export type { ISoulBoundToken } from "./ISoulBoundToken";
