/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as discountDbSol from "./DiscountDB.sol";
export * as interfaces from "./interfaces";
export * as standards from "./standards";
export * as test from "./test";
export { KlayLink__factory } from "./KlayLink__factory";
export { KlayLinkMinter__factory } from "./KlayLinkMinter__factory";
